target:
  backup_list:
       - "/boot"
       - "/usr"
       - "/etc"
       - "/var/lib/apt"
       - "/var/lib/dkms"
       - "/var/lib/dpkg"
       - "/var/lib/man-db"
       - "/var/lib/initramfs-tools"
       - "/var/lib/systemd/deb-systemd-helper-enabled"
       - "/var/lib/selinux"
  hold_list:
       - "/usr/lib/locale/locale-archive"
       - "/etc/locale.gen"
       - "/usr/share/deepin-defender/localcache.db"
  after_run: "/usr/bin/deepin-upgrade-manager-tool --action=notify"

