#!/bin/sh
dir=$(cd $(dirname $0);pwd)
. $(dirname $dir)/functions
. $(dirname $dir)/local
. $(dirname $dir)/nfs

PREREQ=""
prereqs()
{
    echo "${PREREQ}"
}

case "${1}" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

for x in $(cat /proc/cmdline); do
	case $x in
	# The following lines blocked for security reason
	back_version=*)
		back_version=${x#back_version=}
		;;
	esac
done

if [ "x${back_version}" != "x" ]; then
	local_premount_used=yes
	if [ "${readonly}" = "y" ]; then
		mount -o rw,remount ${rootmnt}
		readonly=n
	fi

	if read_fstab_entry /persistent; then
		log_begin_msg "Mounting /persistent file system"
		mountfs /persistent
	fi
	echo "will rollback to ${rootmnt}/persistent/osroot/snapshot/${back_version}"
	deepin-upgrade-manager --config="${rootmnt}/etc/deepin-upgrade-manager/config.json" --action=rollback --version="${back_version}" --root="${rootmnt}"
	if [ "${readonly}" = "n" ]; then
		mount -o ro,remount ${rootmnt}
		readonly=y
	fi
fi