#!/bin/sh
PREREQ=""
prereqs()
{
    echo "${PREREQ}"
}

case "${1}" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /scripts/functions
. /scripts/local
. /scripts/nfs

atomic_upgrade_config=${rootmnt}/etc/deepin-upgrade-manager/config.json
atomic_upgrade_records=${rootmnt}/etc/deepin-upgrade-manager/state.records
repo_records_point_key=repo_mount_point


repo_mount_point=
if test -e ${atomic_upgrade_config}; then
	repo_mount_point=$(echo "$(cat ${atomic_upgrade_config})" | awk -F "[{,:}]" '{for(i=1;i<=NF;i++){if($i~"'${repo_records_point_key}'"){print $(i+1)}}}' | sed 's/\"//g')
fi

if test -n ${repo_mount_point} && test -e ${atomic_upgrade_records};then
	if [ "${readonly}" = "y" ]; then
		mount -o rw,remount ${rootmnt}
		readonly=n
	fi

	if read_fstab_entry ${repo_mount_point}; then
		if [ ${repo_mount_point} != "/" ]; then
			mountfs ${repo_mount_point}
			log_begin_msg "Mounting ${repo_mount_point} file system"
		fi
	fi
	echo "will rollback to ${rootmnt}${repo_mount_point}/osroot/"
	deepin-upgrade-manager --config="${atomic_upgrade_config}" --action=rollback --root="${rootmnt}"
	if [ "${readonly}" = "n" ]; then
		mount -o ro,remount ${rootmnt}
		readonly=y
	fi
fi

